@startuml
!pragma useVerticalIf on
start
repeat :Search Restaurant;
backward :show error;
repeat while (Restaurant available?) is (No) not (yes)
:show restaurant;
:Select Restaurant;
:Show menu;
:Select Items;
:Show totals;
stop
@enduml